### ISSUE TITLE
Toronto Mesh workshop at UofT

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#111]
Had a call with Pegah today about a symposium she is planning at UofT on Saturday, May 25 (~100 people). Wondering if Toronto Mesh would like to facilitate something at event about meshnets and self-managed infrastructure for creative workers, activists, and technologists (e.g. present a little and give markers and paper to draw their ideal communication infra). See more about the event from our [meeting notes](https://hackmd.io/s/r1AJXV7rN#).

**Comment by dasanchez** [comment]
I had a call with Pegah, Connor, and Dawn on March 12. I will join their list of speakers.
Pegah is still working on the schedule/format. More details to follow!

**Comment by benhylau** [comment]
@dasanchez if you plan on doing the drawing exercise, it can possibly be made into a reproducible module in https://github.com/tomeshnet/p2p-internet-workshop/ :)

We talked about this on some of the calls, to have these modular things in next iteration of workshops, alongside activities like [buildyourowninternet](https://github.com/buildyourowninternet/buildyourowninternet.github.io/blob/master/workshop.md)

cc. @Shrinks99 @bennlich @futurefarmer

**Comment by dcwalk** [comment]
There is already a facilitation guide for this activity from the intro to networks workshop I developed 2 years ago: https://github.com/tomeshnet/tomesh.101/blob/master/workshops/intro-to-networks/facilitation-guide.md#section-i-what-we-know-about-computers-and-the-internet

Could very quickly adapt that for this workshop
