### ISSUE TITLE
Speaking opportunity at CivicTechTO

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#112]
As @patcon brought to our attention, CivicTechTO has kindly invited someone from Toronto Mesh to present about the project. Since this project started at CivicTechTO, and it's been a while since we gave an update, this seems like a good time to catch up.

🤔 I wonder if the drawing exercise we will be doing at our [Meet and Greet in Feb](https://tomesh.net/2019-02-21/meet-and-greet/) can be reproduced / adapted for events like this (as breakout after main talk), both to collect ideas of what people would like to see from our project, and as an opportunity to discuss the issues we care about.

**Comment by Shrinks99** [comment]
I like this idea, a "state of the meshnet" type thing could be interesting and also I've never been to CivicTech and I should really get on that at some point!

**Comment by dasanchez** [comment]
I just emailed @patcon about the dates.
We can go over talking points and recent developments when we meet next week 😁

**Comment by dasanchez** [comment]
I'm speaking at CivicTechTO on April 16! Mark your calendars :smile:

**Comment by benhylau** [comment]
@ASoTNetworks streaaaaaaaaaam it!!

**Comment by dasanchez** [comment]
Done! For reference:

The slide deck is in the [tomesh.101 repo](https://github.com/tomeshnet/tomesh.101/tree/master/presentations/20190416_civictechto)
Civic Tech Toronto livestreamed the talk through [YouTube](https://www.youtube.com/watch?v=Qg9-k7tguvI)
