### ISSUE TITLE
CORS on chat.tomesh.net

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#35]
Pasted links:

> "Failed to get preview for https://github.com/tomeshnet/documents/issues/33 Error: CORS request rejected: https://matrix.tomesh.net/_matrix/media/r0/preview_url?url=https%3A%2F%2Fgithub.com%2Ftomeshnet%2Fdocuments%2Fissues%2F33&ts=1473221901572&access_token=MDAxOGxvY2F0aW9uIHRvbWVzaC5uZXQKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI3Y2lkIHVzZXJfaWQgPSBAcHJ1cmlncm86dG9tZXNoLm5ldAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAxZGNpZCB0aW1lIDwgMTQ3MzIyMzUxODI3NwowMDJmc2lnbmF0dXJlILGT2rvagbk-HCayMOLdQJfy7gaktWVae7tAkiz2vufHCg"

**Comment by garrying** [comment]
FYI URL previews are disabled by default: https://github.com/matrix-org/synapse#url-previews

**Comment by benhylau** [comment]
Fixed in https://github.com/tomeshnet/documents/commit/39d1976fba966673a7582474d0d01af7400e22eb by enabling link previews
