### ISSUE TITLE
Public listing of grants and funding opportunities

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#47]
As discussed in our chat, we will keep a public listing of grants and funding opportunities that tomesh is currently pursuing, with their associated deadlines. This page will also list the newly created funding@tomesh.net email for receiving inbound inquiries.

**Comment by dcwalk** [comment]
Sounds good, however is this is a more 'dynamic' doc it might make sense to have 'current opportunities' somewhere else (e.g. a pad, editable doc or sheet) and linked? And historical details about grants/funding giving in here

**Comment by dcwalk** [comment]
I'm counting this as landed by #51, just gonna make another issue for the contacts
