### ISSUE TITLE
Tech update for Planning Meeting

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#83]
- [x] [Test node](https://github.com/tomeshnet/mesh-isp/issues/2) that @darkdrgn2k @Pedro-on-a-bike and @benhylau
- [x] Prototype and Mesh Orange developments
- [x] Workshop series (the tech behind) + upcoming SSBC-grant funded features
- [x] Live streaming project by @ASoTNetworks and @darkdrgn2k 
- [x] Dragino radio module and EspressoBIN router project
- [x] Mapping and monitoring project by @darkdrgn2k 
- [x] Ubiquiti radio testing by @Pedro-on-a-bike (and maybe Dragino radio testing)
- [x] Althea deployment talks

**Comment by dasanchez** [comment]
https://cryptpad.fr/code/#/1/edit/J2FQb-Tm4C1WWq9HRgsZwA/ARzNAhZrH1VpDwEuS1fE1O4z/
