### ISSUE TITLE
Org update at Planning Meeting

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#84]
- [x] Workshop pilot at TPL Fort York and open-source curriculum
- [x] Diversify meeting location effort
- [x] Partnerships (TPL, student housing co-op, etc.)
- [x] Website changes and new room logos / general improving presentation efforts by @Shrinks99 
- [ ] OurNetworks.ca status
- [x] Presentations at UofT, CCC, MaRS, etc.

**Comment by dcwalk** [comment]
Hey! I can't make the planning meeting on Thursday, my updates:

1) Co-op Proposal
a draft was reviewed and revised but never submitted, I can reach out to Sindark if people want to kickstart it, but do not have capacity right now

2) Our Networks
I'd suggest containing the Our Networks conference update so as not to have planning convos happening in multiple places (as this is planned elsewhere). 
So an update might be: New website just went live on Monday and our Call for Participation closed, lots of wonderful submissions. We anticipate a round of announcements late-May including Conf Program, registration, kickoff call for vendors. If people are interested, signing up for updates on the website, sharing with friends, and registering once launched are all great steps! We coordinate on https://github.com/ournetworks/2018 with our meetings schedule published. 

EDIT (and a general life update):
My time will be extremely limited over the next four months and I do not anticipate having bandwidth for Toronto Mesh stuff. I look forward to determining how I can re-engage in the fall.

**Comment by dcwalk** [comment]
Would add: 
- [ ] check-in on who monitors coc@tomesh.net and Code of Conduct (I need to rotate off)
- [ ] check-in on who monitors hello@tomesh.net (I need to rotate off)
- [ ] who leads initiatives/roles, is the governance structure working convo (not to settle anything, but I think it has been brought up at least a few times between meetings)

**Comment by dasanchez** [comment]
Thanks for the input! I started the agenda for Thursday:
https://cryptpad.fr/code/#/1/edit/J2FQb-Tm4C1WWq9HRgsZwA/ARzNAhZrH1VpDwEuS1fE1O4z/

**Comment by benhylau** [comment]
Added a couple small things to the pad

**Comment by dasanchez** [comment]
Added a few details, also moved governance discussion further up to get it out of the way early.

**Comment by dasanchez** [comment]
The [meeting notes](https://github.com/tomeshnet/documents/blob/master/meeting_notes/20180517_planning-meeting-notes.md) have been posted.
