### ISSUE TITLE
Move 'advertising' into the design repo

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/documents#86]
Seems like these graphics should be over there instead of in documents.  If there are any reasons not to move them over post here!

**Comment by benhylau** [comment]
Could be either or? @garrying @dcwalk thoughts?

**Comment by garrying** [comment]
I think the move is fine.

For the design repo's `current-assets` folder, it seems like we're organizing by project name? Maybe we should keep to that for what we're moving over.

**Comment by Shrinks99** [comment]
`current-assets` and `legacy-assets` are both organized by project name.  I'll keep that for these graphics as well.

**Comment by dasanchez** [comment]
Thanks @Shrinks99 👍
