### ISSUE TITLE
Team password management

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/documents#88]
@chrisbarless suggested that we have a 1Password team account. Including:
* Hover
* Email

**Comment by fathert0rque** [comment]
Update: 1Password for teams is $5 USD per user per month. 

Perhaps we could look into an open source solution like [Arc](https://github.com/evilsocket/arc)

**Comment by Shrinks99** [comment]
Closing this, discussion moved [here](https://github.com/tomeshnet/toronto-community-network/issues/38) and mostly completed.
